// AUTH TOKEN KEY
export const STORAGE_TOKEN_KEY = 'token';

export const PLACEMENTTREE_NODE_WIDTH = 200;
export const PLACEMENTTREE_NODE_HEIGHT = 100;
export const PLACEMENTTREE_NODE_X_SPACE = 15;
export const PLACEMENTTREE_NODE_Y_SPACE = 60;

export const COMMISSION_TYPE = {
  PENDING: 'PENDING',
  CONFIRM: 'CONFIRM',
  BLOCK: 'BLOCK',
  NONE: 'NONE',
};
