import type { RESOURCE_TYPE } from 'src/types';

export const RESOURCE_CONTENT: RESOURCE_TYPE[] = [
  {
    header: '#1 - Countdown to Launch',
    description: [
      'Welcome aboard the TEXITcoin (TXC) rocketship!',
      "Whether you're new to cryptocurrency or a seasoned crypto enthusiast, TXC represents a bold new phase in the realm of digital asset exploration. We're doing something unusual, and expecting extraordinary results. There's an easy way to start a new crypto; we're doing it the other way. Why? Because we believe that retaining control of the mine, building it in Texas and not outsourcing it to foreign nations, is the best way possible to keep the future of money honest, fair and prevent it from being another form of manipulation and financial control.",
      "Cryptocurrency is the digital money of the internet—a decentralized medium of exchange that operates without a central authority like a bank. It's a flawless and non counterfeitable unit of account, offering a volatile yet innovative store of value. This concept is absolutely revolutionary in the realm of money and banking. It's the first time in centuries that the market is taking back control of the issuance and security of money.",
      'While cryptocurrency promises freedom and decentralization, challenges persist. Bitcoin, the industry leader, is too expensive to use as a currency. Many cryptocurrencies are controlled by foreign miners, particularly in China, centralizing what should be decentralized. Additionally, few cryptocurrencies are actually used as money or actively advocated for as practical currency.',
      "Although our mission is unique, it's not in any way unrealistic or even particularly difficult. In fact, our key objectives are plainly visible, and all that's left to do is grow and be good stewards of our technology.",
      "As a Miner, you're expected to contribute to the success of our mission, first and foremost by helping grow the mine - a task you have already completed. Moving forward, however, there's much more you can do to ensure our likely success. You are encouraged to participate in any and all ways that are convenient and beneficial for you.",
      "This Mission Control Manual is intended to do just that: introduce you to various components of our mission, bring you up to speed on how they work, and help you engage each when you're ready.",
    ],
    child: [
      {
        title: 'The Crypto Ecosystem',
        content: [
          "Get used to the word “ecosystem”, you're going to hear it a lot in this industry. The word attempts to group the various stakeholders and contributors that make up the various pieces of the puzzle.",
          'Core Technology - TEXITcoin (TXC) is our core technology. TXC started as a clone (copy) of Litecoin (LTC), one of the early alternatives to Bitcoin (BTC). Our development team manages the core technology on a digital code repository and rarely makes changes, fixes or updates to this code. Based on tried and proven code, TXC is a “set and forget” technology that requires little or nothing in the way of ongoing development or maintenance to live on forever.',
          'Layer 1 - when you hear people talking about Layer 1, this means core technology or blockchain. TXC is a Layer 1 cryptocurrency, meaning that it IS its own blockchain and uses its own consensus mechanism to validate transactions and retain a record of balances. Layer 2 technologies are those that are built on top of Layer 1 blockchains, and rely on the foundation Layer to verify transactions. It is easy to build a Layer 2 tech, normally referred to as a “token”. Building a Layer 1 is hard.',
          'Nodes - nodes are servers scattered around the internet that retain a copy of the entire blockchain, and pass transaction information back and forth between participating nodes. In TXC, the nodes that actually accept new blocks are hidden behind firewalls in a private network, and only talk to other nodes that have identified themselves as being authorized to submit new transactions to our network. This is how we prevent unauthorized mining participation.',
          'Mining - this is the term given to the revolutionary process that defines cryptocurrency, and is in fact actually the exotic and ever increasingly difficult cryptographic algorithms that require massive computing power and electricity to perform. In simple terms, the network of computers “mining” a digital Layer 1 cryptocurrency replaces the mainframe computer that a traditional bank would use to keep track of balances and transactions.',
          "Proof of Work (PoW) - how does the cryptocurrency network decide if a transaction is legitimate? It requires an epic amount of work - electricity turned into mathematical equations - to decide if a transaction is genuine. The greater the work, the more valid a transaction is considered. That's why it's so important to keep the mining power in a location that can be trusted. Whoever controls 51% of the mine has the power to manipulate transactions and histories.",
          'MegaHash (mh/s) - the measurement used to rate the performance of a cryptocurrency mining computer, farm or network. A “big” and “trustworthy” mine will process at least 100,000,000 megahashes per second, or mh/s. A megahash is a million hashes per second! So, a powerful crypto mine is able to perform trillions of exotic math computations every second! Not all hash power is created equal, and our algorithm can be easily compared to the performance of the Litecoin and DOGE networks.',
        ],
      },
    ],
  },
  {
    header: '#2 - Securing Your Payload',
    description: [
      "- What wallets are and why they're critical for Miners.",
      '- Types of wallets',
      '- Set up and manage your wallet securely',
      '',
      "The first tool you'll need to begin your journey is a crypto wallet. A crypto wallet is a digital tool that allows you to securely store and manage your cryptocurrency. It keeps your private keys safe and enables you to send, receive, and track your digital assets. Wallets come in various forms, including hot, cold, and exchange wallets. Some wallets hold many various types of digital assets, while others are specifically designed to secure just a single type of crypto. Along your path, you'll use ALL types of wallets, and it's important to know how to tell the difference between good ones and bad, relying exclusively on dependable technology that serves your purposes. Nothing is worse than winning big, just to find out that your wallet was stolen, hacked, corrupted, discontinued or otherwise broken.",
      "From the moment of your very first TXC payout direct from the mine, you're in control of your TXC. There are no controls, locks, limitations or other rules regarding your TXC. It is yours; you own it and can do with it as you please. But, that also means that you're responsible for keeping it safe. We'll get your started with one of our metal Cold Storage Coins; all you have to do is keep this physical item SAFE.",
      "Let's take a quick look at the various types of wallets and get you off to a great start.",
    ],
    child: [
      {
        title: 'Cold Storage Wallet:',
        content: [
          "A cold storage wallet is like a savings account, but offline - more like a safe deposit box. It's disconnected from the internet, offering protection from hackers and other digital threats. Cold wallets are ideal for securely storing larger amounts of cryptocurrency over the long term.",
          "Blockchain Mint (that's us) manufactures an incredibly reliable, easy to use and beautiful metal cold storage wallet, which we call a “Cold Storage Coin”. Manufacturing integrity is our top priority, and we're pleased to boast that every coin we made has worked as designed, flawlessly. This is important because your TXC output from the mine is initially linked to your Cold Storage Coin. All you have to do to keep your seat on the rocket is KEEP THE COIN SAFE.",
          "A cold storage wallet converts digital risk to physical risk; simply stated, instead of hackers and bad computer code, you'll need to worry about physical security instead, including disasters like fires and floods. This is another reason why Cold Storage Coins are so valuable - they're virtually indestructible!",
          "Unfortunately, cold storage wallets do not make spending and trading easy. In fact, because they're offline, they can't be used for these activities at all. Therefore, you'll want to think of your cold storage wallet (especially the Cold Storage Coin you received at signup) like a porcelain piggy bank; keep it safe, add to it from time to time, and crack it open when it's finally time to “cash out”.",
        ],
      },
      {
        title: 'Hot Wallet',
        content: [
          "A hot wallet is like a checking account. It's connected to the internet and designed for frequent transactions, making it convenient but more vulnerable to digital risks. Since a hot wallet is installed on your phone or pc, it's important to create a backup BEFORE you use the wallet so that you can recover your wallet if your phone is lost, stolen, dropped in the toilet or otherwise rendered unusable. The backup code is in the form of either a private key - a long, alphanumeric mix of easily forgettable text, or more recently, in the form of a backup “seed phrase”, also known as a mnemonic recovery phrase. A seed phrase is a collection of usually 12 words (sometimes more) that represent your backup private key. One nice thing about a seed phrase is that it can even be committed to memory, giving you an additional level of peace of mind.",
          "TEXITcoin has developed its own hot wallet that exclusively supports TXC. It gives you the ability to send and receive TXC, see transaction history, and also monitor the “watch only” value of TXC on your Cold Storage Coin. Further, when you're ready, it will quickly import the TXC from your Cold Storage Coin, which you will do preferably when you're ready to “cash out” and monetize the bulk of your TXC.",
          'You can even have multiple TXC hot wallets - each one will have a unique address and backup recovery phrase.',
          "Remember - using a hot wallet opens you up for the first time to the world of “digital risk”, meaning that a hacker, error or lost password could render all of your crypto completely unusable or even stolen. You'll need to use a hot wallet sooner or later, but take your time and become comfortable with backing up, sending and receiving before you engage large amounts of crypto.",
        ],
      },
      {
        title: 'Exchange Wallet',
        content: [
          "An exchange wallet is provided by a 3rd party custodian for storing your digital assets. While convenient, it's not safe for long-term holding. Remember FTX? Mt Gox? Relying on exchanges can leave your funds vulnerable to hacks or mismanagement.",
          "When you store your crypto on an exchange, you're hoping that the exchange will do a good job of securing your digital assets. Rest assured that hackers are working around the clock to gain access to exchange wallets, since they're obvious targets for the taking. On average, an exchange is hacked weekly and the consequences can range from being limited to a particular crypto asset, or devastating and result in the bankruptcy of the exchange. If you trust a 3rd party to keep your crypto safe, you must be aware that you can lose any or all of it without notice or warning.",
        ],
      },
    ],
    footer: [
      "Remember: with wallets hot & cold, there are no “charge-backs”, refunds, do-overs or second chances. If you lock yourself out of a wallet, there is NO way to recover funds. If you send crypto to the wrong address, there's NO way to get it back. If you send the wrong amount, you'll be at the mercy of the recipient to correct this. Transactions with crypto are permanent, by design. This is one of the reasons we love it. But, it's all the more reason to exercise extreme caution when setting up a new wallet, securing your recovery seed phrase, sharing your information with others, sending and receiving crypto.",
    ],
  },
  {
    header: '#3 - Mission Monitoring: Track Your Progress',
    description: [
      '- Tools and platforms for monitoring mining performance.',
      '- How to interpret your mining stats (hashrate, rewards, etc.).',
      '- Setting alerts and maintaining peak performance.',
      '',
      "Managing your TEXITcoin (TXC) portfolio should feel as empowering as it is secure. Here's how to monitor your assets effectively, using the tools we've designed to make your journey with TXC seamless and insightful.",
      "The Blockchain Mint app is the perfect tool for keeping track of your TXC balance on your cold storage coin. Think of it as your “quick glance” dashboard—it doesn't let you send or receive funds, but it gives you peace of mind by displaying your holdings at a glance.",
      "What's even better? The app supports multiple cryptocurrencies. This means you can track a diversified portfolio of various cryptos—always a smart move in the world of digital assets. Diversification helps you tap into the potential upside of different coins, and the Blockchain Mint app makes it simple to stay on top of your holdings.",
      'For more functionality, the TXC Wallet is available on both the App Store and Google Play. Like the Blockchain Mint app, it allows you to track the balance of TXC on your cold storage coin, but with a key difference: this is a watch-only address unless you provide your private key (laser-etched and safely hiding under the tamper-evident security seal on your Cold Storage Coin.',
      'Important notes about the TXC Wallet:',
      '* Digital Risks: The TXC Wallet introduces more complexity. If you fail to back up your seed phrase and lose your phone, your TXC will be lost forever.',
      '* Hot Wallet Caution: Sending TXC from your wallet requires care. Sending funds to the wrong address could make them unrecoverable.',
      '* Exciting Possibilities: While the cold storage coin is secure and straightforward (perfect for those who prefer a “set-it-and-forget-it” approach), the TXC Wallet gives you the flexibility to import your TXC later for transactions, trading, or spending.',
      "The Payout Dashboard is where you connect with the TXC Mine. It's your gateway to:",
      '- Viewing your hash power, referrals, and team performance.',
      "- Accessing an extensive set of charts and data to monitor your contributions and the mission's status.",
      '- Check your referral reward status, Left and Right points, and past cash commissions',
      '',
      "When you're ready, you can even use the Payout Dashboard to change your daily TXC payouts from your Cold Storage Coin to your TXC Wallet.",
      'The Payout Dashboard empowers you to share mission data with friends and family, making it easier to encourage them to join our mission with the confidence of transparency and good decision-making.',
      "The TXC Explorer showcases the beauty of blockchain: total transparency. Here's what you can monitor:",
      '- Every transaction and wallet balance.',
      '- Block counts, the largest TXC holders, and real-time transaction activity.',
      '- Current market price, total market cap, and network health.',
      '',
      "Blockchain is the epitome of honest money, and the TXC Explorer allows you to witness this in action. It's not just about monitoring—it's about trusting the integrity of the network.",
      "Suppose you send a transaction to another TXC Miner or a vendor that accepts TXC as payment. You can quickly look at the TXC Explorer to see if the network has accepted your transaction; if you don't see it packaged into a new block, it means the network is still processing your transfer. Once you see the transaction encoded in a block history, you can rest assured that the transfer is permanent and complete.",
      'CoinMarketCap (CMC) is an independent data aggregator that ranks cryptocurrencies by market capitalization. It provides key metrics like price trends and trading volumes, sourced directly from exchanges trading TXC.',
      "Our expectation is that as TXC grows, the crypto community will discover us on CMC. With this platform, they'll evaluate TXC's performance and decide to trade or invest, amplifying the mission's reach and visibility. Keeping an eye on TXC's performance on CMC is a great way to stay informed about our position in the broader crypto market.",
      'CoinMarketCap also has a robust social media aspect, allowing you to connect with the community on the CMC platform and share your thoughts and insights on the viability of TXC.',
      "By using these tools, you can monitor and manage your TEXITcoin portfolio with confidence, knowing that you're part of a transparent and forward-thinking mission. Whether you're glancing at your balance or diving deep into market data, you're equipped to navigate the cosmos of cryptocurrency.",
    ],
  },
  {
    header: '#4 - Mission Safety Protocols',
    description: [
      '* Understanding and avoiding online scams and other threats.',
      '* Securing your wallet and account.',
      '* Best practices for digital safety.',
      '',
      "Almost as important as choosing the right vehicle for your crypto adventure, is being aware of the various risks and threats associated with the journey. Nothing could be worse than watching your digital fortune slip through your fingers because of an avoidable catastrophe. Let's take a look at the common problems facing our community:",
    ],
    child: [
      {
        title: 'Exchange Drama: Lessons from FTX and Beyond',
        content: [
          'Exchanges can be convenient and are a necessary part of the cryptocurrency ecosystem, but they come with serious risks. The FTX collapse is a cautionary tale:',
          'FTX, once one of the largest and most reputable cryptocurrency exchanges, collapsed in late 2022 in a stunning financial scandal that shook the crypto world. Founded by Sam Bankman-Fried (SBF), FTX gained massive popularity for its user-friendly interface and extensive trading options, quickly becoming a go-to platform for millions of users worldwide.',
          "The collapse began when reports surfaced about questionable financial practices involving FTX and its sister company, Alameda Research. It was revealed that FTX had allegedly used customer funds to cover Alameda's trading losses, a practice that violates basic financial ethics. A leaked balance sheet showed a massive hole in FTX's finances, sparking a liquidity crisis.",
          "As panic spread, users rushed to withdraw their funds, overwhelming FTX's reserves and forcing the exchange to suspend withdrawals. In November 2022, FTX filed for bankruptcy, leaving billions of dollars in customer assets unaccounted for.",
          "The fallout was severe: Investors, including high-profile figures like Tom Brady and Kevin O'Leary, suffered significant losses. Sam Bankman-Fried was arrested and is facing charges of fraud, conspiracy, and money laundering.",
          "The scandal highlighted the risks of centralized exchanges and the importance of transparency and accountability in crypto. While recovery efforts continue, many users have yet to see their funds returned, and FTX's collapse remains a cautionary tale for the crypto industry.",
          'Exchanges are frequent targets for hacks, resulting in stolen funds. Take the potential example of Mt. Gox: ',
          "Mt. Gox, once the world's largest Bitcoin exchange, was at the center of one of the most infamous events in cryptocurrency history. Founded in 2010, Mt. Gox handled over 70% of Bitcoin transactions worldwide at its peak. However, it collapsed in 2014 amid allegations of hacking, fraud, and gross mismanagement.",
          "The trouble began when Mt. Gox reported the theft of 850,000 Bitcoins (worth over $450 million at the time and billions today). The exchange claimed the funds were stolen through a years-long hack exploiting vulnerabilities in its system. Critics, however, argued that the loss stemmed from internal mismanagement and possible foul play by insiders, as Mt. Gox's security practices were notoriously lax.",
          'As the story unfolded, it became clear that Mt. Gox had been insolvent for years, hiding its losses while continuing to operate. In February 2014, the exchange froze withdrawals, filed for bankruptcy, and left users without access to their funds.',
          'The collapse devastated early adopters and eroded trust in cryptocurrency exchanges. While some stolen Bitcoin was later recovered, most users received only a fraction of their original holdings after years of legal battles.',
          "Another issue is KYC (Know Your Customer) compliance. Exchanges often require you to share personal information, and if they flag 'suspicious activity,' they can freeze your account, leaving you powerless. This was one of the many original benefits of decentralized currency, where you get to act as your own bank and control your own funds, without worry of someone like PayPal or a bank locking your account and preventing access to your money.",
          'If you trust someone else to hold your crypto, they control your funds. Keeping your assets on a Cold Storage Coin gives you complete control and removes this risk entirely.',
        ],
      },
      {
        title: 'Man-in-the-Middle Attacks: Beware of Intercepted Transactions',
        content: [
          "A man-in-the-middle attack occurs when someone intercepts your transaction, tricking you into sending your crypto to their wallet instead of the intended address. Here's how to detect and avoid this:",
          '- Always double-check wallet addresses before sending. A single typo could send your funds to the wrong place, often irreversibly.',
          "- When copying and pasting wallet addresses, verify the pasted address matches the original. Some malware can secretly replace the copied address with the attacker's.",
          '- Use QR codes where possible, as they reduce the chances of manual errors.',
        ],
      },
      {
        title: 'Spoofing and Phishing: Stay Skeptical',
        content: [
          "Phishing scams are rampant in the crypto space. Here's how they work:",
          'You receive an email, text, or message claiming to be from a trusted source (like us), asking you to send TXC or share your private keys. The scammer often creates a sense of urgency, like claiming your funds are at risk unless you act quickly. Here are a few key tips:',
          "- We'll never ask you to send TXC or share your private keys.",
          '- Be skeptical of unsolicited requests, especially if they involve sensitive information.',
          '- Look for typos, generic greetings, or suspicious email addresses—common indicators of phishing.',
          "- Other common scams include fake websites, impersonation on social media, and “investment opportunities” promising unrealistic returns. Even if someone you know asks you to help them out or send them something, it's possible their account may have been hacked and you're actually talking to someone completely different.",
        ],
      },
      {
        title: 'User Error',
        content: [
          'While hackers and scammers are real threats, the most common issue in crypto is user error.',
          'Losing your password or recovery key can result in permanent loss of your funds. Writing it down on paper helps, but losing that paper defeats the purpose. We recommend a secure password manager like LastPass to safely store your credentials. Be sure to test your recovery process periodically to ensure you can access your wallet if needed.',
          "One of the most infamous examples of user error in cryptocurrency history is the story of James Howells, a British IT worker who accidentally discarded a hard drive containing 7,500 Bitcoins in 2013. At the time, Bitcoin was still relatively obscure, and those coins were worth a few hundred thousand dollars. Today, they're valued at hundreds of millions of dollars.",
          'Howells was an early Bitcoin miner who began mining in 2009. By 2013, he had stopped mining and stored his Bitcoin wallet on an old laptop hard drive. During a routine cleanup, Howells mistakenly threw the drive away, not realizing its value.',
          'The hard drive ended up in a landfill in Newport, Wales. By the time Howells realized his mistake, it was too late—the landfill covered an area the size of several football fields, with the hard drive buried under thousands of tons of garbage.',
          'Howells has spent years lobbying the local council for permission to excavate the landfill, offering millions of dollars in rewards to anyone who helps recover the drive. Despite his persistence, the council has denied his requests, citing environmental and logistical concerns.',
          "Howells' story highlights the importance of securely storing private keys and wallet backups. Unlike traditional banking, where a lost password can often be reset, cryptocurrency operates on a self-custody model. If you lose access to your wallet, your funds are gone forever.",
          "If you're not actively trading, keeping your TXC on a Cold Storage Coin is the safest option. Cold Storage Coins require no passwords, private keys, or recovery phrases—just keep them physically secure, and your funds are safe. The coins are designed to be redeemed ONCE - they're inexpensive enough so that you can get a new one if you choose to unload and start again!",
          "When you're ready to trade or spend, we recommend leaving your cold storage coin untouched. Instead, modify your mine output to your phone's TXC Wallet. This keeps your long-term holdings safe while giving you access to new funds for trading.",
          "By understanding and preparing for these risks, you can enjoy the benefits of cryptocurrency while keeping your hard-earned assets safe. Crypto can feel like the Wild West at times, but with the right precautions, you'll always have the upper hand. Stay vigilant, stay secure, and happy mining!",
        ],
      },
    ],
  },
  {
    header: '#5 - Meet the Star of the Mission: TXC',
    description: [
      '* Overview of TEXITcoin: what it is and why it matters.',
      '* How TXC is mined and its role in the broader crypto ecosystem.',
      '* The value proposition of TXC and its connection to your mission.',
      '',
      "Understanding the mission and vision of TEXITcoin (TXC) is crucial for every miner. This knowledge ensures you're aligned with our goals and empowers you to effectively communicate our purpose to others. Recruiting new miners isn't just about expanding our network; it's about cultivating a community of advocates who share our commitment to honest money and financial sovereignty.",
      "At the heart of TXC lies a commitment to honest money—a currency that fosters a level playing field and ensures a fair value exchange. We believe that a decentralized currency, free from the control of mega banks, corporations, and foreign entities, is essential for economic freedom and integrity. The work that we do together will achieve this result, and there's no external group or force necessary to establish TXC as a usable form of honest money, to be used and traded by our community.",
      'Our approach involves constructing a mining operation substantial enough to gain respect within the global crypto industry, yet exclusive to Texas. This ensures decentralization and local control, preventing dominance by large external forces. Leveraging our extensive experience in alternative and complementary currencies, we aim to create real-world utility for TXC, integrating it seamlessly into the marketplace.',
      'Cryptocurrency began as a decentralized alternative to traditional finance, promoting financial freedom. However, it has largely devolved into a speculative arena, often manipulated by the wealthy, with its foundational purpose overshadowed by profit motives. Today, a mere 1% of crypto is actually used as a form of payment for goods and services.',
      "This shift presents a unique opportunity for TXC to lead by realigning with crypto's original intent. By offering a quality coin backed by experienced leadership, we can fill the void left by others and reintroduce the true utility of cryptocurrency.",
      "Our success hinges on rapidly building a robust community. We aim to engage around a million individuals to establish a mine that truly matters. Even with a large, active community and practical utility, there's a risk that the global crypto landscape may not immediately acknowledge our efforts. Achieving significant price appreciation requires international markets to recognize and invest in TXC.",
      'Despite these challenges, our mission is clear. By empowering individuals and fostering a decentralized, honest currency, we not only strive for financial success but also advocate for a more equitable economic system. Your role as a miner is pivotal in this journey, and together, we can realize the transformative potential of TEXITcoin.',
      "As you begin to understand our mission, vision and strategy, along with the high likelihood of our success, you'll develop a sense of confidence and eagerness to share the TXC basics with friends, family and colleagues, further ensuring our impending success. Every new Miner on our mission grows the mine and solidifies our forgone conclusion. With greater mission comprehension also comes more engaged Miners - advocates for our success, and cuts down on “buyer's remorse” and disinterested hitchhikers. Simply stated, if you understand what we're doing, you'll be able to explain it to others and bring them with us.",
      'And best of all, if we are successful with our mission, we will be rewarded by getting insanely rich, just as we have seen happen in the case of Bitcoin and many other leading cryptos. The reason for this is because the crypto community will see our commitment to the mission, and want to piggy back on our success and benefit from our upward price. Many of them will get rich along with us.',
    ],
    child: [
      {
        title: 'Our Risks',
        content: [
          'First, can we find, recruit and grow our community large enough and fast enough to matter? We need somewhere around a million people to get the mine big enough to be a force on the global crypto landscape.',
          'With our 100,000,000 (one hundred million) megahash mine, we will regularly ALSO mine competing cryptocurrencies like Litecoin (and DOGE). This is astonishing for several reasons: first, while WE can mine THEM, THEY cannot mine TXC. TEXITcoin is a private mine that keeps out unwanted and unfair competition. Second, there is a strong correlation between the size of the mine and the value of the cryptocurrency it supports. It is extremely conservative to estimate that we will join the list of top-100 coins with this size mine.',
          'This risk, and responsibility, falls squarely on the shoulders of you, our valued Miner. Administratively we can do much of the work - developing technologies, systems, engaging exchanges and promoting our cause. This naturally attracts new Miners to our rocket.',
          "But our community cannot grow quickly beyond a small scale without the real-world validation from trusted friends, relatives, coworkers and other firsthand testimonial experiences. Think about it: you're much more likely to take a risk because it's recommended by a friend, as opposed to plunking down a large chunk of change because of an advertisement you see on late-night TV.",
          "This is why it's so important for you to get and realize a direct and specific benefit from your relationship with TXC. If we create a win - win relationship, and preferably even a win-win relationship where you win more and first, it's likely that you'll share your positive experiences with others. This authentic word-of-mouth advertising cannot be bought and is worth its weight in gold.",
          'Second, will our huge community, with a huge private mine, with real utility and everyday use, actually even register on the global crypto landscape? Although we can be successful in establishing our alternative currency without any external inputs, we still need Japan, China and Korean markets to buy TXC. If TXC is implemented successfully, we will have a legitimate, honest currency to use for goods and services; if foreign markets engage TXC, we will also become insanely rich. Rest assured that we want both. An honest currency in Texas helps Texans. An honest currency worldwide helps everyone, and rewards us for our work by making us extremely rich.',
          'The opportunity, then, is to take a leadership position in crypto because its original use and purpose has largely been abandoned. This creates a niche and market opportunity for a quality coin with real experienced leaders to fill.',
          "We're using a tried and true playbook - something that resembles network marketing - to achieve our goal. We do this because we want the average normal individual to participate and win, and we'd rather put our advertising dollars into affiliate commission instead of purchasing ads on social media networks and becoming dependent on them as gatekeepers of our message.",
        ],
      },
    ],
  },
  {
    header: '#6 - Joining the Galactic Conversation ',
    description: [
      '* Importance of staying connected with fellow miners.',
      '* Official communication channels (forums, social media, events).',
      '* Leveraging the community for support and learning.',
      '',
      "Being part of the TXC mission means you're never alone in your journey. Our community is vibrant, supportive, and full of resources to help you succeed. Here's how to stay connected and engaged:",
      'Our Telegram group is the heart of our active, real-time community. We have more than a dozen topics regularly updated with the very latest from our team. Engage our chat and discuss exchanges, marketplace updates, news, bartering, and more.',
      "Stay in the loop with daily activity, but keep in mind that it can be fast-paced. Regular check-ins will help you avoid feeling overwhelmed. If you're new to Telegram, start by observing discussions before jumping in, and don't hesitate to ask questions!",
      'Every week, the founder hosts a live Zoom call to share mission updates and news, insights into the market and the broader crypto landscape. We also include live training along with q&a to help you grow as a miner and advocate.',
      "Can't make it live? No worries! All calls are recorded and archived in the Payout Dashboard for easy access at your convenience.",
      "We have an extensive collection of short videos and other training materials also archived to the payout system for access later. From time to time, we'll also share links to other quality resources that can be counted on for education and training.",
      "By staying connected through these channels, you'll gain valuable knowledge, build relationships with like-minded individuals, and stay up-to-date on all things TXC. Together, we're not just mining cryptocurrency—we're building a movement.",
    ],
  },
  {
    header: '#7 - Claiming Your Cosmic Rewards',
    description: [
      '* How payouts work and where to track them.',
      '* Navigating the payout dashboard.',
      '* Troubleshooting payout issues.',
      '',
      "The Payout Dashboard is the nerve center of your mining experience, designed to give you control, insight, and the ability to engage with the TXC mission fully. Here's an overview of what you can do and why it matters.",
      "Modify Your TXC Payout - when you're ready to explore the more engaging side of TXC—shopping, spending, and trading—you can redirect your mining payouts to your TXC Wallet instead of your cold storage coin. This is important because not everyone can hold TXC forever. By using it in the market, you help drive adoption and boost its value. TXC isn't just a collectible—it's a functional currency. For it to fulfill its purpose, it needs to be actively used. Turning TXC into real-world value, whether a steak dinner, a new outfit, or a vacation, proves its functionality and profitability. When you spend TXC, you're connecting all the dots and validating the mission.",
      'The dashboard provides an overview of your account information regarding mining activity and allows you to make basic changes. There you can see & confirm your purchased and earned hash power. One of the most exciting aspects of the Payout Dashboard is the ability to manage your team. Here you can also View stats about your referrals and recruits, & track bonuses and cash rewards earned through team-building activities.',
      'While you may be saving most of your TXC for the future, growing your team lets you benefit now by earning rewards that can be used immediately. This dual approach allows you to enjoy short-term gains while still focusing on long-term growth.',
      "The Payout Dashboard is more than just a tool; it's the gateway to unlocking TXC's full potential. By engaging with the dashboard, you're not only contributing to the mission but also reaping the benefits of a functional, real-world currency. Whether you're saving for the future, spending today, or building your team, the dashboard puts the power in your hands.",
      'One important thing to note: your TXC payout will steadily decrease over time. This is by design and easy to understand, once you consider our goals and your involvement. When you join as a Miner, you purchase a specific amount of hash power. Then, if you so desire, you are able to earn more hash power along the journey through our two rewards programs. However, as you add more power, the total hash power of the mine grows. Similarly, as others join the mine, they also increase the total hash power of the mine; this is our major objective. However, as the total mine hash power increases, your hash power will result in a smaller percentage of the total mine power.',
      "For example, suppose you join the mine with the entry level power: 100mh/s. At the time that you join, maybe the total mine power is 200,000mh/s. Therefore, you will receive 100/200,000 of the mine's daily output. If the mine output is 90,000 TXC that day, you will receive 100/200,000 * 90,000, which equals 45 TXC.",
      "Then, a month goes by and the total mine power is now 300,000mh/s. You still have your same 100mh/s, but now this is only 0.03% of the mine output. If the mine produces that day another 90,000 TXC, your payout would decrease to 30 TXC. However, if you qualify for the 1-2-Free bonus by referring 3 new Miners within your first 30 days, you would receive 300mh/s of the mine output, resulting in 0.1% of the mine's output, or 90 TXC on a 90,000 output day.",
      'Therefore, the best way to keep up with the growing mine is by participating in the reward programs, earning more hash power along with the total mine power growth.',
    ],
  },
  {
    header: '#8 - Exchanges: the Interstellar Marketplace',
    description: [
      '* How crypto exchanges work.',
      '* Buying, selling, and trading TXC.',
      '* Choosing the right exchange and understanding fees.',
      '',
      'Exchanges are vital to the cryptocurrency ecosystem, offering a quick and efficient way to convert digital assets like TEXITcoin (TXC) into other digital currencies. Some exchanges, like Coinbase, even allow you to turn digital currencies into fiat money.',
      'Exchanges can be first broken down into two categories: centralized and decentralized. Centralized exchanges (CEX) hold your digital assets and present combinations of trade opportunities (called Trade Pairs), like trading Bitcoin for Ethereum, or Litecoin for Tether. TEXITcoin is only traded on centralized exchanges due to the type of technology it uses.',
      'Centralized exchanges can be broken down into tiers of size and quality. In the world today, there are really only TWO tier-1 exchanges: Coinbase (the largest in the USA) and Binance (the largest exchange in the world).',
      'Tier 2 exchanges are also, generally speaking, reliable and as trustworthy as you can get in this realm. There are about 2 dozen tier-2 exchanges, and they are usually designed to service an exclusive or specific market. For example, UpBit exclusively trades with Korean customers, and only accepts KRW fiat currency for deposit. Generally speaking, it ranks #5 on the top list.',
      'Every other exchange is considered tier-3 or worse. Use tier-3 exchanges extremely sparingly, as they are small, usually under-regulated and likely to fail at any moment.',
      'Decentralized Exchanges (DEX) are used primarily for trading tokens and other Layer-2 cryptos, like SHIB and USDT. Since most tokens are built upon one of three main blockchains (Ethereum, Binance Smart Chain or Solana), these digital asset spinoffs enjoy the luxury of open trading on any decentralized exchange.',
      'Today, trading gold or silver requires physically transporting your assets to a pawn shop or coin dealer, often selling below market value. In the digital realm, crypto exchanges eliminate that hassle, making it easier to quickly convert your digital holdings into something more usable.',
      "For example, you might trade TXC for USDT, and USDT for Bitcoin (BTC), which is accepted at over 54 million businesses worldwide. Or, you could exchange TXC for hundreds of other cryptocurrencies, giving you access to the broader crypto economy. The more exchanges that list TXC and the larger the market of buyers and sellers, the more liquid TXC becomes. Higher liquidity means that you can quickly, easily and inexpensively turn TXC into cold, hard cash and get things that you want, even if those vendors don't directly accept TXC. Greater liquidity also means you can quickly and easily trade TXC without significantly affecting its price. The TXC management team is actively working to add TXC more exchanges, trade pairs and liquidity, ensuring you have plenty of options for trading.",
      "When trading TXC, it's crucial to understand how pricing works: the current market price of TXC is determined by the buyers and sellers, reflecting the value of the most recent trade. Data aggregators like CoinMarketCap will present you with an average market price, based on data collected from participating exchanges. Even though the current market may display a certain price, what you actually get in trade for TXC can vary greatly based on the amount of TXC you want to trade and current market conditions. The price you receive depends on what buyers are willing to pay at that moment, which can change rapidly.",
      'When trading, be sure to choose the right TYPE of order.',
      'Limit Orders - allows you to set the price at which you want to sell. It requires patience, but often results in the best deal if the market moves in your favor.',
      'Market Orders - instantly liquidates your desired quantity of TXC at the current market price. Be cautious—if the market is volatile, you might get less than expected.',
      "Because no one exchange will provide everything you desire for your crypto experience, it's important to learn the basics of moving assets between exchanges.",
      "For example, you will need to do this because the exchanges that support TXC primarily trade TXC for USDT (the Trade Pair), but they will not turn your USDT into cash. In fact, you'll need to use an American-friendly exchange like Coinbase to perform that function. Therefore, you'll use one exchange to convert TXC into USDT, then another exchange to convert USDT into US Dollars, and even place those US Dollars into your bank account. And this process is extremely important: until there's a vibrant community of merchants and business owners that directly accept TXC, you'll need to be comfortable with trading TXC for USDT, then moving USDT to Coinbase and “cashing out”.",
      "Navigating multiple exchanges can be challenging and costly. Exchanges charge for deposits and withdrawals, and blockchain networks have their own transaction fees. When moving digital assets between exchanges, it's best to use a fast and inexpensive cryptocurrency, like Litecoin (LTC), to transfer funds between exchanges. This minimizes costs and speeds up transactions.",
      "Don't leave funds on an exchange. Exchanges are great for trading, but most are not secure for long-term storage. Once your trade is complete, transfer your TXC or other digital assets back to your personal digital wallet or a Cold Storage Coin.",
      'Familiarize yourself with reading exchange charts and understanding market dynamics.',
      "We'll provide videos and screenshots to guide you through setting up accounts and trading on supported exchanges. Using exchanges isn't just about personal benefit; it also strengthens the TXC ecosystem. When you trade TXC, you contribute to its usage and utility. Active trading helps establish TXC as a viable currency, increasing its appeal and value in the market.",
      "By understanding exchanges and using them wisely, you play a crucial role in TXC's journey from a promising digital asset to a globally respected currency.",
    ],
  },
  {
    header: '#9 - The Real Purpose of TXC',
    description: [
      "* How to spend TXC and where it's accepted.",
      '* Encouraging businesses to accept TXC.',
      '* Using TXC in everyday transactions.',
      '',
      'The ultimate goal of TEXITcoin (TXC) is to function as a usable, everyday currency. For that to happen, we need merchants and businesses to accept TXC for goods and services. Our development team is hard at work creating tools and systems to make using TXC…',
      '- Quick: Transactions should be as seamless as swiping a card or tapping a phone.',
      '- Inexpensive: Low fees encourage adoption by both sellers and buyers.',
      '- Extremely Easy: Simplicity is key to getting merchants and customers on board.',
      'These solutions will be available for online merchants and brick-and-mortar shops, ensuring TXC can integrate into daily commerce effortlessly both online and offline.',
      "To accelerate the adoption of TXC, we're focusing on small towns and tight-knit communities, where TXC can serve as a local currency for residents, keeping money circulating within the community and boosting the local economy. We'll introduce TXC at fairs, festivals, and other events where attendees are already familiar with alternative payment systems. This approach creates a gateway for acceptance and helps TXC gain traction with merchants and users.",
      'From these starting points, TXC will grow outward, establishing itself as a trusted medium of exchange.',
      "Once a base of merchants and businesses is established, Miners will play a pivotal role by introducing TXC to producers and sellers. As trade is established, and participants become comfortable with the system, the general public will begin buying, saving, and using TXC as well. Better yet, they'll see the benefits of mining TXC and join the mission themselves!",
      'To ensure you always have a place to spend your TXC, the management team will launch and manage an exclusive e-commerce platform that accepts TXC. Our experienced buyers and trade partners will stock the store with goods and services tailored to your needs. This guarantees that TXC remains valuable, providing a reliable way to exchange it for tangible benefits even if current market conditions prove insufficient for your needs.',
      "Every step of this process is designed to create a thriving ecosystem where TXC is widely accepted by merchants, used by communities to strengthen their local economies, and traded seamlessly in everyday transactions. With your participation, TXC will evolve from a fledgling digital asset into a functional, respected currency that benefits everyone involved. Together, we'll make TXC a globally recognized medium of exchange for the world to enjoy.",
    ],
  },
  {
    header: '#10 - Abandon Ship?',
    description: [
      '* Benefits of long-term participation.',
      '* Identifying areas for optimization.',
      '* Using data to make informed decisions.',
      '',
      "As part of the TXC mission, it's important to reflect on your experience and determine if TXC aligns with your expectations and goals. Here's a guide to help you evaluate whether TXC is the right fit for you:",
      "- Did You Join to Get Rich? If your primary goal was to get rich quickly, it's important to understand that TXC is not a get-rich-quick scheme. Bitcoin took a decade to reach global adoption and a $20,000 per unit price tag, and while we aim to achieve many of our goals by early 2026, patience is key. Please remember that TXC is being built to last, and our mission focuses on building a community and a functional currency with real value; our results transcend the sticker price.",
      '- Are We Making Progress Toward Our Goals? Our success depends on achieving two key objectives: building a community and creating a robust mine. To this end, we encourage you to use the Payout Dashboard to track our growth and velocity, week in and out. Assess whether our results are meeting expectations—are we ahead of or behind schedule?',
      '- Has TXC Made Your Life Better? Take a moment to reflect on your journey with TXC. Have you recovered your initial contribution or made a profit? Have you cashed out some TXC and treated yourself to something meaningful? Consider the ways TXC mining may have had a positive impact on your life, and determine if you think we are continuing on a path that will continue to bear positive results for you as an individual.',
      "- Have You Learned Anything About Crypto? Cryptocurrency is a frontier, and joining TXC is a learning experience. One of our primary responsibilities is to hold your hand as we navigate the digital currency ecosystem; have we done a good job and brought you a greater understanding of the cryptocurrency landscape. Are you more familiar with crypto terms, concepts, and the premise of digital currency? Can you place a monetary value on the knowledge and skills you've gained?",
      "- Did You Engage with the Community? One of our goals is to connect Miners with each other, along with merchants and marketplaces. Have your made friends or built connections through TXC? Have you started using your TXC to 'vote with your wallet' locally or globally with others who share our values?",
      "- Did You Build a Team and Earn Commissions? While TXC matures, we've designed a lucrative compensation plan to reward miners for sharing our mission. Have you earned cash commissions or bonuses? Did you take a moment and learn the basics of teambuilding? We encourage you to take a moment and reflect on how these rewards have supplemented your TXC mining journey.",
      "- Can You Identify Other Improvements in Your Life? Beyond the financial and social aspects, consider any other benefits you've gained from being part of TXC. Has TXC sparked personal growth, new opportunities, or improved skills? Has the TEXITcoin team's energy and drive inspired you to reach for new heights in your life? It's quite possible that our enthusiasm and work ethic rub off on you in ways you don't even notice.",
      '',
      "We value your input and want to ensure TXC meets your expectations. If TXC isn't right for you, let's help you find a way off the rocket with respect and understanding. Your satisfaction and success are crucial to the mission. By reflecting on these questions, you can determine if TXC aligns with your goals and aspirations. Whether you stay on board or choose to exit, we're grateful for your role in the journey so far.",
    ],
  },
  {
    header: '#11 - Broadcast Your Signal',
    description: [
      '* How to introduce others to the mission.',
      "* Tools for sharing TXC's story.",
      '* Encouraging adoption and expanding the community.',
      '',
      'As a TXC miner, your role in our mission extends beyond mining—it includes helping us expand our community. Our success depends on a thriving ecosystem of participants, and we need your help to make that happen. You joined TXC to be part of something successful. To achieve success, we must build a robust ecosystem of:',
      '- Miners: Securing the network and producing TXC.',
      '- Buyers and Sellers: Creating liquidity and establishing a stable value for TXC',
      '- Traders, Merchants, and Businesses: Driving the use of TXC as currency.',
      '- Producers and Consumers: Building a vibrant marketplace.',
      '',
      "We all share the responsibility of expanding this community by inviting others to join us. If you're happy with your TXC experience, we expect you to tell others and encourage their participation. If we all wait for 'someone else' to do it, growth will never happen.",
      "Of course, you're under no obligation to recruit others. For those in our community that want to help expand our network of Miners, we designed an industry-leading affiliate program, offering generous financial incentives to reward you for growing the community.",
      "The smallest affiliate commission is $1,000—more than most miners contribute initially. By referring as few as 6 new miners, you'll earn back more than most people put in. This equates to a 16% commission in traditional terms. If you build a team of miners who also recruit, we'll pay you based on the results of your entire team, not just your own efforts.",
      "Best of all, direct referrals increase your hash power, giving you a larger percentage of the mine's output. The biggest advocates of TXC should reap the greatest rewards—it's only fair.",
      "As you promote TXC and bring in friends, family, business associates, and other participants, you help grow the community. In return, we grow the mine incrementally to match your efforts. The bigger the community, the larger the mine—and the more valuable TXC becomes. Our approach ensures that in the realm of mining, we're competing with each other, not with banks, corporations, or foreign nations. If you find your mining output decreasing, it simply means that the size of the mine, along with the community of advocates and Miners, is growing, which is expected to have a positive impact on the value of TXC in the open market.",
      "Leading miners with the greatest TXC output won't necessarily be those with the deepest pockets. Instead, they'll be the individuals who champion our cause most effectively and bring on the greatest number of new Miners. Since no miner is allowed to buy more than 900 mh/s with their own cash, large quantities of hash power must be earned with bonuses, commissions or other rewards.",
      "Our mission is vast, and our rocket can accommodate up to 1 million miners. While we prioritize access for Texans and Americans, we reserve a small portion for international participants. This ensures our trade partners around the world have a meaningful vested interest in TXC's success.",
      "By spreading the word, you're not just helping us grow—you're securing your own success as well. Together, we'll build a vibrant community and a powerful mine that fuels TXC's rise as a functional, respected currency. Let's share the mission and make history!",
    ],
  },
  {
    header: '#12 - Assemble Your Crew',
    description: [
      '* Strategies for building a mining team.',
      '* Tips for effective communication and collaboration.',
      '* Leadership insights for managing and inspiring your crew.',
      '',
      "Managing a team in the TXC ecosystem is a critical step in maximizing your success. Here's a detailed guide to understanding how our team structure works and how to make the most of our binary compensation plan.",
      "Before continuing, however, it's important to clarify one point, as you'll likely come across this objection as you share your experience with others: TXC uses some terminology familiar to MLMs—like 'binary,' 'comp plan,' 'downline,' and 'team.' While we may sound similar, there are key differences:",
      "No recruiting required: You're not obligated to bring others on board to benefit from the mine. Your mine hash power pays out directly to you, each and every day. New babies and retired Miners receive TXC from the mine just like everyone else.",
      "One-time fee: There's no monthly auto-ship or recurring costs, the hallmark of most network marketing schemes. Instead of having a garage full of shampoos and lotions, you'll be stuck with an evergreen supply of TXC that will be instantly available for spending, trading, safe-keeping or even cashing out later.",
      "Product-focused: We're here to mine TXC, not sell lotions or miracle products.",
      '',
      "Even so, we acknowledge that many MLMs work. Even ones that have terrible products, confusing comp plans and slimy leadership, still seem to become billion dollar endeavors. Despite their flaws, many MLMs succeed because they offer a low barrier to entry and empower individuals to start earning quickly. Our model takes the best aspects of network marketing—community-building and incentives—without the baggage. Now, quite confident in our system's ability to achieve our major goals, we are secure enough in our success to embrace the similarities and point out the significant differences. Others will make their own conclusions regarding what we are or seem to be. We encourage skeptics to join us, try it out, and see the difference first-hand. And since more than 20 million Americans participate in MLM, we have a great community of networkers to reach and invite to do it better with us.",
    ],
    child: [
      {
        title: 'Affiliate Rewards: Two Ways to Earn',
        content: [
          'For every three miners you directly sponsor, the mine will grow by 100 MH/s in your favor.',
          "If you achieve this within your first 30 days, we'll add a bonus of 200 MH/s instead of the normal 100 mh/s, meaning miners joining at entry-level can triple their output by recruiting just three others. For every additional set of three miners, you'll earn another 100 MH/s with no limit.",
          'This ensures that our biggest advocates earn the greatest share of TXC mining power.',
          'Additionally, TXC offers team-based rewards, operating in a binary structure with two legs: left and right. After filling your first two spots - left and right, future recruits must be placed under existing team members, either on the left leg or right leg. A binary structure means that each miner has two direct placements: one on their left and one on their right.',
          'Once these two spots are filled, all additional recruits must be placed beneath existing members in either the left or right leg. This creates a stacked structure where your recruits benefit those both above and below them.',
          "At the end of each week, we calculate the points in your left and right legs. For every three points on your left leg matched by three points on your right leg, you'll earn a $1,000 cash reward (up to a maximum of $3,000 per week).",
          "Unused points roll over; up to 9 points carry over to the next week if unmatched. Points are cumulative, and you'll earn points from anyone the results of everyone in your team, whether they're your direct recruits or from others in your team.",
          "There is some good news, and some “bad news”: the good news is that points come from anywhere in your team, down to infinity. You're not limited to just your direct recruits. The “bad news” is that we only count up to 9 points per week. If your team generates more than 9 points, you'll still be capped at $3,000 for that week, and only up to 9 unmatched points roll over.",
          "While it may seem restrictive at first, this system encourages team leaders to focus on helping their teammates succeed, rather than hoarding points or recruits. Over time, your earnings will come less from personal recruiting and more from your team's success.",
          "If you have earned a cash commission, you can opt for a 'BOGO' hash power upgrade. In this scenario, your $1,000 commission can purchase 200 MH/s of hash power. This is a great way for team builders to acquire greater amounts of hash power - far in excess of the new cash purchase limit, since this cash is already part of the TXC ecosystem. There's no limit to the number of BOGO upgrades you can earn, ensuring that your leadership efforts translate into greater mining output.",
          "With our aggressive and simple binary compensation plan, you'll notice your points accumulating quickly and turning into weekly payouts even when you have not directly sponsored any new Miners. When this takes place, we think of you as a team leader, with your job not just to recruit—but instead to manage, train and inspire your team effectively.",
          "Use the Payout Dashboard to monitor your team's growth, track points, and decide where to place new miners. You can help your teammates succeed by encouraging your team to recruit and earn their own rewards. A strong team benefits everyone. Once commissions are processed for a weekly period, team placement cannot be modified. Plan carefully to maximize success for yourself and your team.",
          'Our compensation plan is designed to reward advocates who drive the mission forward:',
          '- By recruiting, you grow the mine and the community.',
          '- By building a team, you help others succeed and earn from your combined efforts.',
          "- By stacking hash power and rewards, you maximize your mining output while growing TXC's ecosystem.",
          '',
          'It is our job to help you configure your team to get the most out of the binary compensation plan.',
          "If you are experienced in binary compensation plans, you will have your own ideas on how to build a team for maximum personal or team benefit. However, we will encourage you to build your team so that you make it as easy as possible for your teammates to also earn cash commissions. Many on the rocket are new to this type of affiliate compensation plan, and it may take a little practice, trial & error to get it just right. Once your team is set and commission is processed for a period, placement cannot be modified. Please review each week and let us know before Saturday at noon if you notice any issues or need to make any modifications. TXC's system is transparent, fair, and designed for long-term success. Together, we're building more than a mine—we're building a movement.",
          'Using payout, you can see your team grow, count your current points, and decide appropriate placement for new Miners based on your desires, the dynamics of your team, and other personal preferences.',
        ],
      },
    ],
  },
  {
    header: '#13 - TEXITcoin: a Mission that Matters',
    description: [
      "TXC isn't just another cryptocurrency; it's a bold experiment in creating honest money, empowering individuals, and fostering a decentralized financial system rooted in integrity and purpose.",
      "You've joined a mission with a clear goal: to establish TXC as a usable, respected currency that benefits everyone involved. By mining, learning, connecting, and sharing, you're contributing to a movement that prioritizes community, utility, and long-term success over short-term gains.",
      "This isn't a passive endeavor. TXC thrives on your participation:",
      '- Grow the community by sharing the mission and bringing others on board.',
      '- Use TXC to unlock its potential as a functional currency.',
      "- Build your team and earn rewards while contributing to the ecosystem's growth.",
      '',
      "While the road ahead will have challenges, it's also filled with opportunity. Together, we're proving that a decentralized currency can have real-world impact, not just as a speculative asset but as a practical, everyday tool for trade, commerce, and community-building.",
      "The future of TXC depends on us all. Stay engaged, stay informed, and keep mining—not just for coins, but for the shared vision of a better financial system. Welcome aboard the rocket, and let's make history together. 🚀",
    ],
  },
];
